/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSigns;
import Business.VitalSignsHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahit
 */
public class abnormalJPanel extends javax.swing.JPanel {
private VitalSignsHistory vsh;
private double minbp;
private double maxbp;
    /**
     * Creates new form abnormalJPanel
     */
    public abnormalJPanel(VitalSignsHistory vsh,double minbp, double maxbp) {
        initComponents();
        this.vsh=vsh;
        this.minbp=minbp;
        this.maxbp=maxbp;
        displayVitalSigns();
        
    }
public void displayVitalSigns(){
    DefaultTableModel dtm=(DefaultTableModel)VitalSignstbl.getModel();
    dtm.setRowCount(0);
    label:
    for(VitalSigns vs:vsh.getVitalSignsHistory()){
        if((vs.getBloodPressure()<minbp) || (vs.getBloodPressure()>maxbp))
        {Object row[]=new Object[2];
       
        row[0]=vs;
        row[1]=vs.getBloodPressure();
        dtm.addRow(row);}
        continue label;
    }
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignstbl = new javax.swing.JTable();
        ViewDetailsBtn = new javax.swing.JButton();
        Update1Btn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        temparatureTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        ConfirmBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        VitalSignstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VitalSignstbl);

        ViewDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ViewDetailsBtn.setText("Details");
        ViewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsBtnActionPerformed(evt);
            }
        });

        Update1Btn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Update1Btn.setText("Update");
        Update1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update1BtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Blood Pressure : ");

        bloodPressureTextField.setEnabled(false);
        bloodPressureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodPressureTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Temparature : ");

        temparatureTextField.setEnabled(false);
        temparatureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temparatureTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Pulse : ");

        pulseTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Date : ");

        dateTextField.setEnabled(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ConfirmBtn.setText("confirm");
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Abnormal Vital Sign");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(temparatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(ConfirmBtn)))
                .addGap(0, 0, 0))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeleteBtn)
                                    .addComponent(ViewDetailsBtn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(Update1Btn)))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(ViewDetailsBtn)
                        .addGap(43, 43, 43)
                        .addComponent(DeleteBtn)
                        .addGap(40, 40, 40)
                        .addComponent(Update1Btn)))
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(temparatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(ConfirmBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsBtnActionPerformed

        int selectedRow=VitalSignstbl.getSelectedRow();
        if(selectedRow>=0){
            VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
            bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
            temparatureTextField.setText(String.valueOf(vs.getTemparature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(String.valueOf(vs.getDate()));
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row you want to view");
        }
    }//GEN-LAST:event_ViewDetailsBtnActionPerformed

    private void Update1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update1BtnActionPerformed
        int selectedRow=VitalSignstbl.getSelectedRow();
        if(selectedRow>=0){
            setAllEnabled(true);
            VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
            bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure() + ""));
            temparatureTextField.setText(String.valueOf(vs.getTemparature()+ ""));
            pulseTextField.setText(String.valueOf(vs.getPulse()+ ""));
            dateTextField.setText(String.valueOf(vs.getDate()));
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row you want to update");
        }
    }//GEN-LAST:event_Update1BtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedRow=VitalSignstbl.getSelectedRow();
        if(selectedRow>=0){
            VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
            int dialogButton=0;
            int dialogResult=JOptionPane.showConfirmDialog (null, "Are you sure you want to delete selected row","Warning",dialogButton);

            if (dialogResult == JOptionPane.YES_OPTION) {

                vsh.deleteVitalSign(vs);

                JOptionPane.showMessageDialog(null,"Deleted successfully");
                displayVitalSigns();} }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void bloodPressureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodPressureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureTextFieldActionPerformed

    private void temparatureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temparatureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temparatureTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed

        int selectedRow=VitalSignstbl.getSelectedRow();
        if(selectedRow>=0){
            VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
            double bp=Double.parseDouble(bloodPressureTextField.getText());
            double t=Double.parseDouble(temparatureTextField.getText());
            int p=Integer.parseInt(pulseTextField.getText());
            String d =dateTextField.getText();
            vs.setBloodPressure(bp);
            vs.setPulse(p);
            vs.setTemparature(t);
            vs.setDate(d);
            displayVitalSigns();
            setAllEnabled(false);
             bloodPressureTextField.setText("");
       temparatureTextField.setText("");
       pulseTextField.setText("");
      dateTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row");}
    }//GEN-LAST:event_ConfirmBtnActionPerformed


    private void setAllEnabled(boolean b){
         bloodPressureTextField.setEnabled(b);
       temparatureTextField.setEnabled(b);
       pulseTextField.setEnabled(b);
      dateTextField.setEnabled(b);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton Update1Btn;
    private javax.swing.JButton ViewDetailsBtn;
    private javax.swing.JTable VitalSignstbl;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTextField temparatureTextField;
    // End of variables declaration//GEN-END:variables
}
