/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSigns;
import Business.VitalSignsHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahit
 */
public class ViewPanel extends javax.swing.JPanel {
private VitalSignsHistory vsh;
    /**
     * Creates new form ViewPanel
     * @param vsh
     */
    public ViewPanel(VitalSignsHistory vsh) {
        initComponents();
        this.vsh=vsh;
        displayVitalSigns();
        }
public void displayVitalSigns(){
    DefaultTableModel dtm=(DefaultTableModel)VitalSignstbl.getModel();
    dtm.setRowCount(0);
    for(VitalSigns vs:vsh.getVitalSignsHistory()){
        Object row[]=new Object[2];
        row[0]=vs;
        row[1]=vs.getBloodPressure();
        dtm.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignstbl = new javax.swing.JTable();
        Update1Btn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        temparatureTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        ViewDetailsBtn = new javax.swing.JButton();
        ConfirmBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        VitalSignstbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        VitalSignstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VitalSignstbl);

        Update1Btn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Update1Btn.setText("Update");
        Update1Btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update1BtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Blood Pressure : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Temparature : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Pulse : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Date : ");

        bloodPressureTextField.setEnabled(false);
        bloodPressureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodPressureTextFieldActionPerformed(evt);
            }
        });

        temparatureTextField.setEnabled(false);
        temparatureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temparatureTextFieldActionPerformed(evt);
            }
        });

        pulseTextField.setEnabled(false);

        dateTextField.setEnabled(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        ViewDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ViewDetailsBtn.setText("Details");
        ViewDetailsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsBtnActionPerformed(evt);
            }
        });

        ConfirmBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ConfirmBtn.setText("confirm");
        ConfirmBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("View Vital Sign");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temparatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(15, 15, 15)
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Update1Btn)
                            .addComponent(ViewDetailsBtn)
                            .addComponent(DeleteBtn))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ViewDetailsBtn)
                        .addGap(48, 48, 48)
                        .addComponent(Update1Btn)
                        .addGap(61, 61, 61)
                        .addComponent(DeleteBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(temparatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmBtn))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Update1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update1BtnActionPerformed
      int selectedRow=VitalSignstbl.getSelectedRow();
      if(selectedRow>=0){
           setAllEnabled(true);
          VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
         bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure() + ""));
       temparatureTextField.setText(String.valueOf(vs.getTemparature()+ ""));
       pulseTextField.setText(String.valueOf(vs.getPulse()+ ""));
      dateTextField.setText(String.valueOf(vs.getDate()));
          }
      else{
JOptionPane.showMessageDialog(null,"Please select a row you want to update");
      }
    }//GEN-LAST:event_Update1BtnActionPerformed

    private void bloodPressureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodPressureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureTextFieldActionPerformed

    private void temparatureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temparatureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temparatureTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
 int selectedRow=VitalSignstbl.getSelectedRow();
      if(selectedRow>=0){
          VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
           int dialogButton=0;
        int dialogResult=JOptionPane.showConfirmDialog (null, "Are you sure you want to delete selected row","Warning",dialogButton);

    if (dialogResult == JOptionPane.YES_OPTION) { 

           vsh.deleteVitalSign(vs);
          
       JOptionPane.showMessageDialog(null,"Deleted successfully");
          displayVitalSigns();} }
      else{
JOptionPane.showMessageDialog(null,"Please select a row");
      }        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ViewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsBtnActionPerformed

        int selectedRow=VitalSignstbl.getSelectedRow();
      if(selectedRow>=0){
          VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
         bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
       temparatureTextField.setText(String.valueOf(vs.getTemparature()));
       pulseTextField.setText(String.valueOf(vs.getPulse()));
      dateTextField.setText(String.valueOf(vs.getDate()));
          }
      else{
JOptionPane.showMessageDialog(null,"Please select a row you want to view");
      }
    }//GEN-LAST:event_ViewDetailsBtnActionPerformed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
            
         int selectedRow=VitalSignstbl.getSelectedRow();
      if(selectedRow>=0){
          VitalSigns vs=(VitalSigns)VitalSignstbl.getValueAt(selectedRow,0);
          double bp=Double.parseDouble(bloodPressureTextField.getText());
       double t=Double.parseDouble(temparatureTextField.getText());
       int p=Integer.parseInt(pulseTextField.getText());
       String d =dateTextField.getText();
       vs.setBloodPressure(bp);
          vs.setPulse(p);
             vs.setTemparature(t);
                vs.setDate(d);
                 displayVitalSigns();
                 setAllEnabled(false);
                  bloodPressureTextField.setText("");
       temparatureTextField.setText("");
       pulseTextField.setText("");
      dateTextField.setText("");
                 
      }
      else{
JOptionPane.showMessageDialog(null,"Please select a row");}
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    private void setAllEnabled(boolean b){
         bloodPressureTextField.setEnabled(b);
       temparatureTextField.setEnabled(b);
       pulseTextField.setEnabled(b);
      dateTextField.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton Update1Btn;
    private javax.swing.JButton ViewDetailsBtn;
    private javax.swing.JTable VitalSignstbl;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JTextField temparatureTextField;
    // End of variables declaration//GEN-END:variables
}
